name: test
on: 
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo test
