name: test-and-document
on: 
  pull-request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    container: rust:latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo test
